# https://corepunk.wiki/w/Logging
# https://corepunk.pro/professions/logging
# https://corepunkers.com/professions

- name: Amber
  rarity: Green
  source: Magic Tree
  wiki: https://corepunk.wiki/w/Amber

- name: Blood Honey
  rarity: Purple

- name: Jewellery Wood
  items:
    Tree Root: 3

- name: Mana Resin
  rarity: Green
  source: Magic Tree

- name: Mutated Leaf
  rarity: Blue
  source: Magic Tree

- name: Neon Mushroom
  rarity: Blue
  source: Magic Tree

- name: Silica
  items:
    Stone Bark: 3

- name: Tissue Paper
  items:
    Wood: 3

- name: Transparent Leaf
  rarity: Green
  source: Magic Tree

- name: Treated Wood
  items:
    Heartwood: 3