- name: Jewellery Wood
  items:
    Tree Root: 3

- name: Silica
  items:
    Stone Bark: 3

- name: Tissue Paper
  items:
    Wood: 3

- name: Treated Wood
  items:
    Heartwood: 3

- name: Mana Resin
  rarity: Green
  source: Magic Tree
  
- name: Transparent Leaf
  rarity: Green
  source: Magic Tree